# Hoja de Trabajo #2 - Universidad del Valle de Guatemala
- Diego Leiva 
- Jose Pablo Orellana
- María Marta Ramirez - 21438
---------------------------------------------------------------------------------------------------

imports

In [5]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import torch
from torch.utils.data import TensorDataset, DataLoader
import torch.nn.functional as F
import torch.nn as nn

## Task 1 - Preparacion del dataset

cargar data

In [3]:
# Cargar dataset
iris = load_iris()
X = iris.data
y = iris.target

# mostrar head de los datos
print(X[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


dividir la data en conjunto de entrenamiento y validacion

In [4]:
# Dividir el dataset en entrenamiento y validación
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Convertir a tensores de PyTorch
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.long)
X_val = torch.tensor(X_val, dtype=torch.float32)
y_val = torch.tensor(y_val, dtype=torch.long)

# Crear DataLoader
train_dataset = TensorDataset(X_train, y_train)
val_dataset = TensorDataset(X_val, y_val)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16)

## Task 2 - Arquitectura modelo

In [6]:
class FeedforwardNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(FeedforwardNN, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.fc3 = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# Definir parámetros del modelo
input_size = 4  # Número de características en el dataset de Iris
hidden_size = 16 # Número de neuronas en la capa oculta
output_size = 3  # Tres clases en el dataset de Iris

model = FeedforwardNN(input_size, hidden_size, output_size)
